name: Label PRs

on:
- pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: srvaroa/labeler@master
      env:
        GITHUB_TOKEN: "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"